name: Zed Build
on: 
  workflow_dispatch:
env: 
  RUSTFLAGS: '-C target-cpu=zen2 -C opt-level=3 -C link-arg=-z -C link-arg=pack-relative-relocs -C link-arg=-fuse-ld=lld -C linker=clang'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: "Checkout latest Zed commit"
        uses: actions/checkout@v4
        with:
          repository:  'zed-industries/zed'
          submodules: 'recursive'  
      - name: "Setup Rust Toolchain"
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: "Install MinGW"
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            curl
            clang
            lld
            llvm
      - name: "Build Zed for Windows"
        run: "cargo build --release --target x86_64-pc-windows-gnu"
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: zed
          path: target/release/Zed.exe
